package vista;

/**
 * Ventana principal de la aplicación.
 * 
 * @author Ricardo Arce.
 */
public class FormVentanaPrincipal extends javax.swing.JFrame {

  /**
   * Constructor de la clase FormVentanaPrincipal.
   */
  public FormVentanaPrincipal() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    cbOperacion = new javax.swing.JComboBox<>();
    jLabel2 = new javax.swing.JLabel();
    cbAlgoritmo = new javax.swing.JComboBox<>();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtSalida = new javax.swing.JTextArea();
    jScrollPane2 = new javax.swing.JScrollPane();
    txtEntrada = new javax.swing.JTextArea();
    btEnviarCorreo = new javax.swing.JButton();
    btSalir = new javax.swing.JButton();
    btCifrar = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    btCargarArchivo = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(30, 33, 36));
    jPanel1.setPreferredSize(new java.awt.Dimension(910, 570));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Operación:");

    cbOperacion.setBackground(new java.awt.Color(40, 43, 48));
    cbOperacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    cbOperacion.setForeground(new java.awt.Color(255, 255, 255));
    cbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cifrar", "Descifrar" }));

    jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Algoritmo:");

    cbAlgoritmo.setBackground(new java.awt.Color(40, 43, 48));
    cbAlgoritmo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    cbAlgoritmo.setForeground(new java.awt.Color(255, 255, 255));
    cbAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "César", "Llave", "Vigenére", "Palabra inversa", "Mensaje inverso", "Código telefónico", "Codificación binaria", "RSA", "DES", "AES" }));
    cbAlgoritmo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbAlgoritmoActionPerformed(evt);
      }
    });

    txtSalida.setBackground(new java.awt.Color(40, 43, 48));
    txtSalida.setColumns(20);
    txtSalida.setForeground(new java.awt.Color(255, 255, 255));
    txtSalida.setRows(5);
    txtSalida.setBorder(null);
    txtSalida.setCaretColor(new java.awt.Color(255, 255, 255));
    jScrollPane1.setViewportView(txtSalida);

    txtEntrada.setBackground(new java.awt.Color(40, 43, 48));
    txtEntrada.setColumns(20);
    txtEntrada.setForeground(new java.awt.Color(255, 255, 255));
    txtEntrada.setRows(5);
    txtEntrada.setBorder(null);
    txtEntrada.setCaretColor(new java.awt.Color(255, 255, 255));
    txtEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    jScrollPane2.setViewportView(txtEntrada);

    btEnviarCorreo.setBackground(new java.awt.Color(54, 57, 62));
    btEnviarCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btEnviarCorreo.setForeground(new java.awt.Color(255, 255, 255));
    btEnviarCorreo.setText("Enviar por correo");
    btEnviarCorreo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btEnviarCorreoActionPerformed(evt);
      }
    });

    btSalir.setBackground(new java.awt.Color(54, 57, 62));
    btSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btSalir.setForeground(new java.awt.Color(255, 255, 255));
    btSalir.setText("Salir");
    btSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btSalirActionPerformed(evt);
      }
    });

    btCifrar.setBackground(new java.awt.Color(54, 57, 62));
    btCifrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btCifrar.setForeground(new java.awt.Color(255, 255, 255));
    btCifrar.setText("Cifrar texto");
    btCifrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btCifrarActionPerformed(evt);
      }
    });

    jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Salida");

    jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("Entrada");

    btCargarArchivo.setBackground(new java.awt.Color(54, 57, 62));
    btCargarArchivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btCargarArchivo.setForeground(new java.awt.Color(255, 255, 255));
    btCargarArchivo.setText("Cargar archivo de texto");
    btCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btCargarArchivoActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(53, 53, 53)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btCargarArchivo)
            .addGap(20, 20, 20))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
              .addComponent(jLabel4)
              .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel3)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEnviarCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        .addContainerGap(33, Short.MAX_VALUE))
    );

    jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(28, 28, 28)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btCargarArchivo)
          .addComponent(cbAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2)
          .addComponent(cbOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addGap(37, 37, 37)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btEnviarCorreo)
          .addComponent(btSalir)
          .addComponent(btCifrar))
        .addGap(25, 25, 25))
    );

    jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbOperacion, jLabel1});

    jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbAlgoritmo, jLabel2});

    jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

    jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btCifrar, btEnviarCorreo, btSalir});

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cbAlgoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlgoritmoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_cbAlgoritmoActionPerformed

  private void btEnviarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarCorreoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btEnviarCorreoActionPerformed

  private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btSalirActionPerformed

  private void btCifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCifrarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btCifrarActionPerformed

  private void btCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargarArchivoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btCargarArchivoActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btCargarArchivo;
  public javax.swing.JButton btCifrar;
  public javax.swing.JButton btEnviarCorreo;
  public javax.swing.JButton btSalir;
  public javax.swing.JComboBox<String> cbAlgoritmo;
  public javax.swing.JComboBox<String> cbOperacion;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  public javax.swing.JTextArea txtEntrada;
  public javax.swing.JTextArea txtSalida;
  // End of variables declaration//GEN-END:variables
}
